include:
  - project: sre/gitlab-ci-templates
    ref: v1.0.5
    file:
      - /shared/build-and-push-image.yml
      - /shared/deploy-kubefiles.yml

stages:
  - sync-content
  - build
  - image
  - deploy-staging
  - deploy-production

sync-content:
  stage: sync-content
  image: taptap-img-registry.cn-beijing.cr.aliyuncs.com/public/deploy-tools:alpine3.12
  only:
    - pipelines
  script:
    - bash .ci/sync_content.sh

build:
  stage: build
  image: node:15.12
  before_script:
    - yarn --version
    - yarn install
  script:
    - 'node_modules/.bin/docusaurus build --out-dir build-cn'
    - 'git checkout intl && TDS_REGION=hk node_modules/.bin/docusaurus build --out-dir build-hk'
  cache:
    key: ${CI_COMMIT_REF_SLUG}
    paths:
      - node_modules
  artifacts:
    paths:
      - build-cn
      - build-hk
  except:
    - pipelines
  only:
    - master
    - auto-sync

build-and-push-image:
  stage: image
  extends:
    - .build-and-push-image
  variables:
    DOCKER_REGISTRY_NAMESPACE: tds
    DOCKER_REGISTRY_REPO: tapsdkdoc
  dependencies:
    - build
  except:
    - pipelines
  only:
    - master
    - auto-sync

deploy-staging:
  stage: deploy-staging
  extends:
    - .deploy-kubefiles-staging
  variables:
    PROJECT_PATH: tds/tapsdkdoc
  needs:
    - build-and-push-image
  when: on_success
  except:
    - pipelines
  only:
    - master
    - auto-sync

deploy-production:
  stage: deploy-production
  extends:
    - .deploy-kubefiles-production
  variables:
    PROJECT_PATH: tds/tapsdkdoc
  needs:
    - deploy-staging
  only:
    - master
